; Generated by c86 (BYU-NASM) 5.1 (beta) from ISRHandlers.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
YKTickNum:
	DW	0
	ALIGN	2
KeyboardHandler:
	; >>>>> Line:	15
	; >>>>> void KeyboardHandler(void){ 
	jmp	L_ISRHandlers_1
L_ISRHandlers_2:
	; >>>>> Line:	17
	; >>>>> c = KeyBuffer; 
	mov	al, byte [KeyBuffer]
	mov	byte [bp-1], al
	mov	sp, bp
	pop	bp
	ret
L_ISRHandlers_1:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_ISRHandlers_2
	ALIGN	2
YKTickHandler:
	; >>>>> Line:	36
	; >>>>> void YKTickHandler(){ 
	jmp	L_ISRHandlers_4
L_ISRHandlers_5:
	; >>>>> Line:	38
	; >>>>> ++YKTickNum; 
	inc	word [YKTickNum]
	; >>>>> Line:	47
	; >>>>> YKUpdateSuspendedTasks(); 
	call	YKUpdateSuspendedTasks
	mov	sp, bp
	pop	bp
	ret
L_ISRHandlers_4:
	push	bp
	mov	bp, sp
	jmp	L_ISRHandlers_5
	ALIGN	2
STGameOverHandler:
	; >>>>> Line:	51
	; >>>>> void STGameOverHandler(){ 
	jmp	L_ISRHandlers_7
L_ISRHandlers_8:
	; >>>>> Line:	53
	; >>>>> } 
	mov	sp, bp
	pop	bp
	ret
L_ISRHandlers_7:
	push	bp
	mov	bp, sp
	jmp	L_ISRHandlers_8
	ALIGN	2
STNewPieceHandler:
	; >>>>> Line:	54
	; >>>>> void STNewPieceHandler(){ 
	jmp	L_ISRHandlers_10
L_ISRHandlers_11:
	; >>>>> Line:	56
	; >>>>> } 
	mov	sp, bp
	pop	bp
	ret
L_ISRHandlers_10:
	push	bp
	mov	bp, sp
	jmp	L_ISRHandlers_11
	ALIGN	2
STReceivedHandler:
	; >>>>> Line:	57
	; >>>>> void STReceivedHandler(){ 
	jmp	L_ISRHandlers_13
L_ISRHandlers_14:
	; >>>>> Line:	59
	; >>>>> } 
	mov	sp, bp
	pop	bp
	ret
L_ISRHandlers_13:
	push	bp
	mov	bp, sp
	jmp	L_ISRHandlers_14
	ALIGN	2
STTouchdownHandler:
	; >>>>> Line:	60
	; >>>>> void STTouchdownHandler(){ 
	jmp	L_ISRHandlers_16
L_ISRHandlers_17:
	; >>>>> Line:	62
	; >>>>> } 
	mov	sp, bp
	pop	bp
	ret
L_ISRHandlers_16:
	push	bp
	mov	bp, sp
	jmp	L_ISRHandlers_17
