; Generated by c86 (BYU-NASM) 5.1 (beta) from ISRHandlers.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
L_ISRHandlers_4:
	DB	") IGNORED",0
L_ISRHandlers_3:
	DB	"KEYPRESS (",0
L_ISRHandlers_2:
	DB	"DELAY COMPLETE",0
L_ISRHandlers_1:
	DB	"DELAY KEY PRESSED",0
	ALIGN	2
KeyboardHandler:
	; >>>>> Line:	4
	; >>>>> void KeyboardHandler(void){ 
	jmp	L_ISRHandlers_5
L_ISRHandlers_6:
	; >>>>> Line:	6
	; >>>>> if(((char) KeyBuffer) == 'd'){ 
	cmp	byte [KeyBuffer], 100
	jne	L_ISRHandlers_7
	; >>>>> Line:	7
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	8
	; >>>>> printString("DELAY KEY PRESSED"); 
	mov	ax, L_ISRHandlers_1
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	9
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	10
	; >>>>> for(i = 0; i < 5000; i++){} 
	mov	word [bp-2], 0
	jmp	L_ISRHandlers_9
L_ISRHandlers_8:
L_ISRHandlers_11:
	; >>>>> Line:	10
	; >>>>> for(i = 0; i < 5000; i++){} 
	inc	word [bp-2]
L_ISRHandlers_9:
	cmp	word [bp-2], 5000
	jl	L_ISRHandlers_8
L_ISRHandlers_10:
	; >>>>> Line:	11
	; >>>>> printString("DELAY COMPLETE"); 
	mov	ax, L_ISRHandlers_2
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	12
	; >>>>> printNewLine(); 
	call	printNewLine
	jmp	L_ISRHandlers_12
L_ISRHandlers_7:
	; >>>>> Line:	14
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	15
	; >>>>> printString("KEYPRESS ("); 
	mov	ax, L_ISRHandlers_3
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	16
	; >>>>> printChar((char) KeyBuffer); 
	push	word [KeyBuffer]
	call	printChar
	add	sp, 2
	; >>>>> Line:	17
	; >>>>> printString(") IGNORED"); 
	mov	ax, L_ISRHandlers_4
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	18
	; >>>>> printNewLine(); 
	call	printNewLine
L_ISRHandlers_12:
	mov	sp, bp
	pop	bp
	ret
L_ISRHandlers_5:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_ISRHandlers_6
